- repo: https://github.com/AleksaC/jsonschema
  rev: 9b31e6368
  hooks:
    - id: validate
      files: |
        (?x)(
          ^valid.json$ |
          ^invalid.json$
        )
      args: ["--schema", "schema.json"]

    - id: validate
      files: |
        (?x)(
          ^valid.json$
        )
      args: ["--schema", "schema.json"]

    - id: validate
      files: |
        (?x)(
          ^invalid.json$
        )
      args: ["--schema", "schema.json"]
